drop table if exists retail;

create table retail(
customer_id int PRIMARY KEY,
age varchar(20), 
gender varchar(20), 
item_purchased varchar(20), 
category varchar(20),
purchase_amount  int ,
location_ varchar(20),
size_ varchar(20), 
color varchar(20), 
season varchar(20),
review_rating NUMERIC(2, 1),
subscription_status boolean, 
shipping_type varchar(20),
discount_applied boolean, 
previous_purchases int , 
payment_method varchar(20),
frequency_of_purchases varchar(20),
age_group varchar(20), 
purchase_frequency_days int
);
select * from retail;
select count(*)from retail;


--Q1. What is the total revenue generated by male vs. female customers?

select gender, sum(purchase_amount) as purchase
from retail
group by gender
order by purchase DESC;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 

select customer_id, purchase_amount 
from retail 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from retail)

-- Q3. Which are the top 5 products with the highest average review rating?

select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating"
from retail
group by item_purchased
order by avg(review_rating) desc
limit 5

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select shipping_type, 
ROUND(AVG(purchase_amount),2)
from retail
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM retail
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM retail
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM retail)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category? 

WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM retail
    GROUP BY category,item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM retail
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 

SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM retail
GROUP BY age_group
ORDER BY total_revenue desc;

--Q11. Rank customers within each location by total spend (top spender per state).

WITH ranked AS (
    SELECT customer_id, location_, purchase_amount,
           RANK() OVER (PARTITION BY location_ ORDER BY purchase_amount DESC) AS spend_rank
    FROM retail
) 
SELECT * FROM ranked WHERE spend_rank = 1;

--Q14. Which payment method is most preferred within each season?
	
WITH payment_counts AS (
    SELECT season, payment_method, COUNT(*) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY season ORDER BY COUNT(*) DESC) AS rnk
    FROM retail
    GROUP BY season, payment_method
)
SELECT season, payment_method, total_orders
FROM payment_counts
WHERE rnk = 1;

--Q15. Which products have both high sales volume and high customer ratings?

SELECT 
    item_purchased,
    COUNT(*) AS sales_volume,
    ROUND(AVG(review_rating), 2) AS avg_rating
FROM retail
GROUP BY item_purchased
HAVING COUNT(*) >= 100
   AND AVG(review_rating) >= 4
ORDER BY sales_volume DESC, avg_rating DESC;

--Q16. Which customer age group has the highest average purchase value

SELECT 
    age_group,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_value
FROM retail
GROUP BY age_group
ORDER BY avg_purchase_value DESC
LIMIT 1;